// <auto-generated />
using System;
using ARinspection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ARinspection.Migrations
{
    [DbContext(typeof(PecaContext))]
    [Migration("20260116172132_MigracaoCompleta")]
    partial class MigracaoCompleta
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("ARinspection.Models.PecaModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoricoJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Instrucao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Temperatura")
                        .HasColumnType("REAL");

                    b.Property<double>("Vibracao")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("people");
                });
#pragma warning restore 612, 618
        }
    }
}
